### ISSUE TITLE
Why not keep the same key combination to remove/delete logs as turboConsoleLog?

### ISSUE THREAD

**Issue by SotoAugusto** [DeveloperEstiven/turbo-system-debug#6]
I recently discovered your extension and think it's fantastic! I have a suggestion: why not align with turboConsoleLog and set `ctrl+alt+d `/ `ctrl+opt+d` as the default shortcut for deleting debug messages?

I find `ctrl+alt+e` a bit confusing. With the Salesforce extension pack, the suggested key combination doesn't conflict with any other shortcuts.

I managed to change it myself by overwriting the command turbo-apex-debug.removeAll. If you'd like, I can create a PR to add this configuration to the README. It would be great to have this as the default setting!

Thanks for creating this extension!

**Comment by Gonzalez-S** [comment]
Hey @SotoAugusto, thanks a lot for the feedback! I'm glad I could simplify the process for someone, even just a little.
Yes, I completely agree with you. Changing the shortcut to the default one used by turbo-console-log makes it more consistent. I just updated the README and the extension – now that's the default shortcut. Thanks again! ❤️
